### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by msteiger** [Terasology/Pathfinding#5]
Currently, 38 out of 40 tests fail with

```
java.lang.RuntimeException: Failed to find natives from .jar launch
at org.terasology.engine.paths.PathManager.<init>(PathManager.java:70)
at org.terasology.engine.paths.PathManager.getInstance(PathManager.java:121)
at org.terasology.HeadlessEnvironment.setupPathManager(HeadlessEnvironment.java:218)
at org.terasology.Environment.reset(Environment.java:53)
```

I suspect that this is related to the [config change in build 105](http://jenkins.movingblocks.net/view/Modules/job/Pathfinding/jobConfigHistory/showDiffFiles?timestamp1=2014-02-04_19-00-03&timestamp2=2014-04-24_05-32-58).
##

**Comment by jdrueckert** [comment]
@casals Is this still the case?

**Comment by keturn** [comment]
there _are_ some current test failures, and I think some of the same conditions still apply, but enough things have changed in gradle and ModuleManager since 2014 that I am going to close this report as stale.
